# Generated by Django 4.2.7 on 2023-12-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
