# Generated by Django 4.2.7 on 2023-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="userid",
            field=models.IntegerField(default=2238010021, max_length=12),
            preserve_default=False,
        ),
    ]
