# Generated by Django 4.2.7 on 2023-11-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userid",
            field=models.BigIntegerField(),
        ),
    ]
