# Generated by Django 4.2.7 on 2023-11-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sem",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
