# Generated by Django 4.2.7 on 2023-11-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_options_user_unique_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sem",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "first semester"),
                    (1, "second semester"),
                    (1, "third semester"),
                    (1, "fourth semester"),
                    (1, "fifth semester"),
                    (1, "sixth semester"),
                    (1, "seventh semester"),
                    (1, "eigth semester"),
                ],
                null=True,
            ),
        ),
    ]
