# Generated by Django 4.2.7 on 2023-11-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_sem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sem",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "first semester"),
                    (2, "second semester"),
                    (3, "third semester"),
                    (4, "fourth semester"),
                    (5, "fifth semester"),
                    (6, "sixth semester"),
                    (7, "seventh semester"),
                    (8, "eigth semester"),
                ],
                null=True,
            ),
        ),
    ]
