# Generated by Django 4.2.7 on 2023-11-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_user_sem"),
    ]

    operations = [
        migrations.CreateModel(
            name="subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept",
                    models.CharField(
                        choices=[
                            ("IT", "Information Technology"),
                            ("CSE", "Computer Science"),
                            ("AI&ML", "Artificial Intelligence and Machine Learning"),
                        ],
                        max_length=45,
                    ),
                ),
                (
                    "sem",
                    models.CharField(
                        choices=[
                            (1, "first semester"),
                            (2, "second semester"),
                            (3, "third semester"),
                            (4, "fourth semester"),
                            (5, "fifth semester"),
                            (6, "sixth semester"),
                            (7, "seventh semester"),
                            (8, "eigth semester"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject_name", models.CharField(max_length=45, null=True)),
                (
                    "subject_code",
                    models.CharField(max_length=10, null=True, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("theory", "Theory"),
                            ("lab", "Lab"),
                            ("genral", "genral"),
                        ],
                        max_length=45,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
