# Generated by Django 4.2.7 on 2023-11-28 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="attendance_pool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "recieved_attendance",
                    models.IntegerField(blank=True, default=0, max_length=150),
                ),
                (
                    "dept",
                    models.CharField(
                        choices=[
                            ("IT", "Information Technology"),
                            ("CSE", "Computer Science"),
                            ("AI&ML", "Artificial Intelligence and Machine Learning"),
                        ],
                        max_length=45,
                    ),
                ),
                (
                    "sem",
                    models.CharField(
                        choices=[
                            (1, "first semester"),
                            (2, "second semester"),
                            (3, "third semester"),
                            (4, "fourth semester"),
                            (5, "fifth semester"),
                            (6, "sixth semester"),
                            (7, "seventh semester"),
                            (8, "eigth semester"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_alive", models.BooleanField(default=True, null=True)),
                (
                    "created_by",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_pool",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.subject"
                    ),
                ),
            ],
        ),
    ]
