# Generated by Django 4.2.7 on 2023-11-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("present", "Present"), ("absent", "Absent")],
                default="absent",
                max_length=20,
            ),
        ),
    ]
