# Generated by Django 4.2.7 on 2023-11-28 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="student_roll",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="attendance_pool",
            name="recieved_attendance",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name="request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_roll", models.IntegerField()),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("late", "late attendance"),
                            ("leave", "request leave"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.attendance_pool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
