# Generated by Django 4.2.7 on 2023-11-30 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_attendance_pool_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_pool',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='attendance_pool',
            name='sem',
        ),
        migrations.AlterField(
            model_name='attendance_pool',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
