# Generated by Django 4.2.7 on 2023-12-01 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_attendance_pool_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='handling_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
