# Generated by Django 4.2.7 on 2023-12-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_subject_handling_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab'), ('genral', 'genral')], max_length=45),
        ),
    ]
