# Generated by Django 4.2.7 on 2023-12-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.BigIntegerField(null=True),
        ),
    ]
