# Generated by Django 4.2.7 on 2023-12-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.IntegerField(choices=[(0, 'teacher'), (1, 'first semester'), (2, 'second semester'), (3, 'third semester'), (4, 'fourth semester'), (5, 'fifth semester'), (6, 'sixth semester'), (7, 'seventh semester'), (8, 'eigth semester')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='sem',
            field=models.IntegerField(blank=True, choices=[(0, 'teacher'), (1, 'first semester'), (2, 'second semester'), (3, 'third semester'), (4, 'fourth semester'), (5, 'fifth semester'), (6, 'sixth semester'), (7, 'seventh semester'), (8, 'eigth semester')], null=True),
        ),
    ]
