# Generated by Django 4.2.7 on 2023-12-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_rename_request_attendance_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_pool',
            name='datefield',
            field=models.DateField(auto_now=True),
        ),
    ]
