# Generated by Django 4.2.7 on 2023-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_attendance_pool_datefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_pool',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_pool',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
