# Generated by Django 4.2.7 on 2023-12-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_attendance_pool_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_pool',
            name='datefield',
            field=models.DateField(auto_now_add=True),
        ),
    ]
